-- MySQL Script generated by MySQL Workbench
-- Wed Apr  9 01:13:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
SHOW WARNINGS;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`producer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `default_schema`.`producer` (
  `producer_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`producer_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `default_schema`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`movie` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `default_schema`.`movie` (
  `movie_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `rating` VARCHAR(10) NULL DEFAULT NULL,
  `producer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`),
  CONSTRAINT ``
    FOREIGN KEY (`producer_id`)
    REFERENCES `default_schema`.`producer` (`producer_id`));

SHOW WARNINGS;
CREATE INDEX ON `default_schema`.`movie` (`producer_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `default_schema`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`actor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `default_schema`.`actor` (
  `actor_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`actor_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `default_schema`.`movie_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`movie_actor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `default_schema`.`movie_actor` (
  `movie_id` INT NULL DEFAULT NULL,
  `actor_id` INT NULL DEFAULT NULL,
  `role_type` VARCHAR(20) NULL DEFAULT NULL,
  `payment_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`, `actor_id`),
  CONSTRAINT ``
    FOREIGN KEY (`movie_id`)
    REFERENCES `default_schema`.`movie` (`movie_id`),
  CONSTRAINT ``
    FOREIGN KEY (`actor_id`)
    REFERENCES `default_schema`.`actor` (`actor_id`));

SHOW WARNINGS;
CREATE INDEX ON `default_schema`.`movie_actor` (`actor_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `default_schema`.`theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`theatre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `default_schema`.`theatre` (
  `theatre_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `ticket_price` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`theatre_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `default_schema`.`movie_theatre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `default_schema`.`movie_theatre` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `default_schema`.`movie_theatre` (
  `movie_id` INT NULL DEFAULT NULL,
  `theatre_id` INT NULL DEFAULT NULL,
  `tickets_sold` INT NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`, `theatre_id`),
  CONSTRAINT ``
    FOREIGN KEY (`movie_id`)
    REFERENCES `default_schema`.`movie` (`movie_id`),
  CONSTRAINT ``
    FOREIGN KEY (`theatre_id`)
    REFERENCES `default_schema`.`theatre` (`theatre_id`));

SHOW WARNINGS;
CREATE INDEX ON `default_schema`.`movie_theatre` (`theatre_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
